# Generated by Django 4.0.10 on 2023-03-01 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simple_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10000)),
                ('members', models.ManyToManyField(related_name='groups_joined', to='simple_users.simpleuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='simple_users.simpleuser')),
            ],
        ),
    ]
